
# GitHub Action that builds the website and commits again

name: autobuild
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
            ref: ${{ github.head_ref }}
      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13
          architecture: 'x64'
      - run: pip install -r requirements.txt
      - name: Run Pelican (build website)
        env:
          DOK_API_KEY: ${{ secrets.DOK_API_KEY }}
        run: make github
